name: Sync upstream develop branch

on:
  repository_dispatch:
    types: [sync-develop]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "${{ secrets.EMAIL }}"

      - name: Add upstream and sync
        run: |
          git remote add upstream https://github.com/anhyeryeon2/Algoing
          git fetch upstream
          git checkout develop
          git merge upstream/develop --allow-unrelated-histories --no-edit || echo "Already up to date"
          git push origin develop
